services: 

  proxy:
    image: nginx:1.27.2
    volumes:
      - ./nginx/conf-proxy:/etc/nginx/conf.d/
      # - ./nginx/certs:/etc/nginx/certs/
    ports:
      - 80:80
      - 443:443
    networks:
      - pabx
    extra_hosts:
      - host.docker.internal:host-gateway

  static-files:
    image: nginx:1.27.2
    volumes:
      - ./nginx/conf-static:/etc/nginx/conf.d/
      - ./varSpoolAsterisk/recording/mp3s:/var/www/app/static/:ro
    networks:
      - pabx

  asterisk:
    build: ./docker-asterisk
    network_mode: host
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ./asterisk:/etc/asterisk:ro
      - ./varLibAsterisk:/var/lib/asterisk
      - ./varLogAsterisk:/var/log/asterisk
      - ./varSpoolAsterisk:/var/spool/asterisk
    logging:
      driver: none
    # restart: on-failure


networks:
  pabx:
