services: 

  asterisk:
    build: ./docker-asterisk
    network_mode: host
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ./asterisk:/etc/asterisk:ro
      - ./varLibAsterisk:/var/lib/asterisk
      - ./varLogAsterisk:/var/log/asterisk
      - ./audios:/audios
    logging:
      driver: none
    # restart: on-failure

#   api:
#     build: ./docker-api
#     environment:
#       - TZ=America/Sao_Paulo
#       - ASTERISK_HOST=host.docker.internal
#       - VIP_HOST=http://host.docker.internal:8080
#     extra_hosts:
#       - "host.docker.internal:host-gateway"
#     volumes: 
#       - ./asterisk:/asterisk
#     ports:
#       - "8000:8080"
#       - "4573:4573"
#     networks:
#       - pabx


# networks:
#   pabx:
