services: 

  proxy:
    image: nginx:1.27.2
    volumes:
      - ./nginx/conf-proxy:/etc/nginx/conf.d/
      # - ./nginx/certs:/etc/nginx/certs/
    ports:
      - 80:80
      - 443:443
    networks:
      - pabx

  static-files:
    image: nginx:1.27.2
    volumes:
      - ./nginx/conf-static:/etc/nginx/conf.d/
      - ./audios/records/mp3s:/var/www/app/static/:ro
    networks:
      - pabx

  api:
    build: ./docker-api
    environment:
      - TZ=America/Sao_Paulo
      - ASTERISK_HOST=host.docker.internal
      - VIP_HOST=http://host.docker.internal:8080
      - PABX_TRUNK=TWILLIO_JUPITER
      - PABX_TECH_PREFIX=101#
      - IASMIN_BACKEND_URL=https://iasmin-5bffa268e5ef.herokuapp.com
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes: 
      - ./asterisk:/asterisk
      - ./audios:/audios
    ports:
      - "4573:4573"
    networks:
      - pabx

  asterisk:
    build: ./docker-asterisk
    network_mode: host
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ./asterisk:/etc/asterisk:ro
      - ./varLibAsterisk:/var/lib/asterisk
      - ./varLogAsterisk:/var/log/asterisk
      - ./audios:/audios
    logging:
      driver: none
    # restart: on-failure


networks:
  pabx:
