[general]
static=yes
writeprotect=yes
autofallthrough=yes

[globals]

[HANGUP-ACTIONS]
exten => h,1,Noop(EXECUTANDO HANGUP DE ${CONTEXT})

[INVALID-ACTIONS]
exten => i,1,NoCdr
    same => n,Noop(EXECUTANDO INVALID DE ${CONTEXT})

[FAILED-ACTIONS]
exten => f,1,NoCdr
    same => n,Noop(EXECUTANDO FAILED DO CONTEXTO ${CONTEXT})

[VIP-REGISTERS]
include => HANGUP-ACTIONS
include => INVALID-ACTIONS
include => FAILED-ACTIONS

exten => _X!,1,Set(ARRAY(CDR(peer),CDR(company))=${REPLACE(CALLERID(num),_,\,)})
    same => n,Noop(${UNIQUEID} >> CHAMADA DE ${CALLERID(all)} PARA ${EXTEN} EMPRESA ${CDR(company)} SIP-CALLID ${PJSIP_HEADER(read,Call-ID)})
    same => n,Set(CDR(userfield)=OUTBOUND)
    same => n,Set(CHANNEL(language)=${PJSIP_HEADER(read,X-Language)})
    same => n,Stasis(outbound-router-call,${CDR(peer)},${CDR(company)},${EXTEN})
    same => n,Hangup

exten => _*X!,1,Set(ARRAY(CDR(peer),CDR(company))=${REPLACE(CALLERID(num),_,\,)})
    same => n,Noop(>>> CAPTURANDO DE ${CALLERID(all)} PARA ${EXTEN} EMPRESA ${CDR(company)})
    same => n,NoCdr
    same => n,Stasis(outbound-router-call,${CDR(peer)},${CDR(company)},${EXTEN})
    same => n,Hangup

[VIP-TRUNKS]
include => HANGUP-ACTIONS
include => INVALID-ACTIONS
include => FAILED-ACTIONS

exten => _X!,1,Noop(${UNIQUEID} >> CHAMADA DE ${CALLERID(all)} PARA ${EXTEN} EMPRESA ${CDR(company)} SIP-CALLID ${PJSIP_HEADER(read,Call-ID)})
    same => n,Set(CDR(userfield)=INBOUND)
    same => n,Stasis(outbound-router-call,${CALLERID(num)},${CDR(company)},${EXTEN},INBOUND)
    same => n,Hangup
