[general]
static=yes
writeprotect=yes
autofallthrough=yes

[globals]

[HANGUP-ACTIONS]
exten => h,1,Noop(EXECUTANDO HANGUP DO CONTEXTO ${CONTEXT})

[INVALID-ACTIONS]
exten => i,1,NoCdr
    same => n,Noop(EXECUTANDO INVALID DO CONTEXTO ${CONTEXT})
    same => n,Answer
    same => n,Playback(invalid)
    same => n,Hangup

[FAILED-ACTIONS]
exten => f,1,NoCdr
    same => n,Noop(EXECUTANDO FAILED DO CONTEXTO ${CONTEXT})
    same => n,Hangup

[CALL-LIMIT-EXCEEDED]
exten => call-limit,1,NoCdr
    same => n,Noop(LIMITE DE CANAIS ${CALL_LIMIT} EXCEDIDO)
    same => n,Hangup

[VIP-PEERS]
include => HANGUP-ACTIONS
include => INVALID-ACTIONS
include => FAILED-ACTIONS
include => CALL-LIMIT-EXCEEDED

exten => _X!,1,Noop(>>> CHAMADA DE ${CALLERID(all)} PARA ${EXTEN} EMPRESA ${CDR(company)})
    same => n,GotoIf($[${GROUP_COUNT(${CDR(peer)})} > ${CALL_LIMIT}]?call-limit,1)
    same => n,Stasis(outbound-router-call-app)
    same => n,Hangup

exten => _*X!,1,Noop(>>> LIGAGAO DE FACILIDADE DE ${CALLERID(all)} PARA ${EXTEN} EMPRESA ${CDR(company)})
    same => n,Stasis(outbound-router-call-app)
    same => n,Hangup

[TEST]
include => HANGUP-ACTIONS
include => INVALID-ACTIONS
include => FAILED-ACTIONS

exten => _X!,1,Noop(${UNIQUEID} >> CHAMADA DE TEST SAIDA DE ${CALLERID(all)} PARA ${EXTEN} EMPRESA ${CDR(company)} SIP CALLID ${PJSIP_HEADER(read,Call-ID)})
    same => n,NoCdr
    same => n,GoSub(find-best-worker,s,1)
    same => n,Set(CALLERID(num)=${CDR(peer)}_${CDR(company)})
    same => n,Dial(PJSIP/${EXTEN}@${WORKER},30,b(pre-dial^s^1(${CHANNEL(language)})))
    same => n,Hangup

[find-best-worker]
exten => s,1,Set(WORKER=WORKER1)
    same => n,Set(CURLOPT(httptimeout)=1)
    same => n,Set(CURLOPT(failurecodes)=500,501,502,503,504,28,7,6)
    same => n,Set(CURL_RESPONSE=${CURL(https://veia.vipsolutions.com.br/vip-status-manager/channels/asterisk)})
    same => n,GotoIf($[${EXISTS(${CURL_RESPONSE})}]?:use-default)
    same => n,Set(WORKER=${CURL_RESPONSE})
    same => n(use-default),Noop(>>> DEFINIDO WORKER ${WORKER})
    same => n,Return()

[pre-dial]
exten => s,1,Set(PJSIP_HEADER(add,X-Language)=${ARG1})
    same => n,Return()