[global]
endpoint_identifier_order=ip,username

;=============== TRANSPORT DEFAULT

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0
;; rede(s) locais (ajuste para sua LAN)
local_net=172.18.0.0/16
;; IP público/externo do Asterisk (substitua pelo seu IP público)
external_signaling_address=201.23.73.16
external_media_address=201.23.73.16


;===============INCLUDES
#include pjsip-trunks.conf
;===============INCLUDES


