[global]
endpoint_identifier_order=ip,username

;=============== TRANSPORT DEFAULT

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0
;; rede(s) locais (ajuste para sua LAN)
local_net=172.18.0.0/16
;; IP público/externo do Asterisk (substitua pelo seu IP público)
external_signaling_address=201.23.72.128
external_media_address=201.23.72.128

;; Basic IPv6 UDP transport
;[transport-udp-ipv6]
;type=transport
;protocol=udp
;bind=::


[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0
;; rede(s) locais (ajuste para sua LAN)
local_net=172.18.0.0/16
;; IP público/externo do Asterisk (substitua pelo seu IP público)
external_signaling_address=201.23.72.128
external_media_address=201.23.72.128

[transport-tls]
type=transport
protocol=tls
bind=0.0.0.0:5061
cert_file=/etc/asterisk/keys/vipsolutions_com_br_full.crt
priv_key_file=/etc/asterisk/keys/server.key
method=sslv23

[transport-wss]
type=transport
protocol=wss
bind=0.0.0.0
; All other transport parameters are ignored for wss transports.


;===============INCLUDES
#include pjsip-peers.conf
#include pjsip-trunks.conf
;===============INCLUDES

;=============== AUTH: jefao
[jefao]
type=auth
auth_type=md5
username=credencial
md5_cred=1ebf905894879a8631824e8b8e30b521

;;=============== ENDPOINT: WEB
[web]
type=endpoint
transport=transport-wss
webrtc=yes
context=TEST
callerid=Web teste
language=pt_BR
dtmf_mode=rfc4733
disallow=all
allow=alaw
auth=jefao
aors=web
;; media direto quando possível
direct_media = no

set_var=CDR(company)=100023
set_var=CDR(peer)=31
set_var=PEER_DDR=1154201020
set_var=CALL_LIMIT=2
set_var=GROUP()=31
set_var=__TRANSFER_CONTEXT=TRANSFERING

;=============== AORS: WEB
[web]
type=aor
qualify_frequency=0
max_contacts=2
